server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka
  instance:
    instance-id: payment9001
    prefer-ip-address: true

spring:
  application:
    name: cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/tang05709/SpringCloudCg.git #GitHub上面的git仓库名字
          # search-paths: SpringCloudCg #搜索目录
      label: master #读取分支
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

